version: '3.9'

services:
  web:
    image: mymh/sg01g02mvc:latest
    container_name: sg01g02mvc-web
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - appnet

networks:
  appnet: