name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Logga in på Azure med service principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Hämta hemligheter från Key Vault
      - name: Get secrets from Key Vault
        id: getSecrets
        run: |
          VAULT_NAME="sg01g02kv606my1"
          echo "DOCKERHUB_USERNAME=$(az keyvault secret show --name 'dockerhub-username' --vault-name "$VAULT_NAME" --query 'value' -o tsv)" >> $GITHUB_ENV
          echo "DOCKERHUB_TOKEN=$(az keyvault secret show --name 'dockerhub-token' --vault-name "$VAULT_NAME" --query 'value' -o tsv)" >> $GITHUB_ENV
          echo "WATCHTOWER_TOKEN=$(az keyvault secret show --name 'watchtower-token' --vault-name "$VAULT_NAME" --query 'value' -o tsv)" >> $GITHUB_ENV
          echo "WATCHTOWER_ENDPOINT=http://$(az keyvault secret show --name 'reverse-proxy-ip' --vault-name "$VAULT_NAME" --query 'value' -o tsv):8080" >> $GITHUB_ENV

      # Gör ett test här som kollar att hemligheterna är hämtade
      - name: Verify secrets were retrieved
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "Error: DOCKERHUB_USERNAME is not set"
            exit 1
          fi

          if [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "Error: DOCKERHUB_TOKEN is not set"
            exit 1
          fi

          if [ -z "$WATCHTOWER_TOKEN" ]; then
            echo "Error: WATCHTOWER_TOKEN is not set"
            exit 1
          fi

          if [ -z "$WATCHTOWER_ENDPOINT" ]; then
            echo "Error: WATCHTOWER_ENDPOINT is not set"
            exit 1
          fi

          # Maskera hemligheterna i loggen men visa att de existerar
          echo "DOCKERHUB_USERNAME exists"
          echo "DOCKERHUB_TOKEN exists"
          echo "WATCHTOWER_TOKEN exists"
          echo "WATCHTOWER_ENDPOINT: $WATCHTOWER_ENDPOINT"

          echo "All required secrets were successfully retrieved from Key Vault!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mymh/sg01g02mvc:latest

      - name: Notify Watchtower
        run: |
          curl -H "Authorization: Bearer ${{ env.WATCHTOWER_TOKEN }}" ${{ env.WATCHTOWER_ENDPOINT }}/v1/update